import { Inter } from "next/font/google";
import Head from "next/head";
import { SignUp, Welcome } from "ui";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const value = 101010;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome doc={value} />
      <main>Welcome to client</main>
      <SignUp />
    </>
  );
}
